### ISSUE TITLE
Multiple instances of minstructor can result in data being overwritten

### ISSUE THREAD

**Issue by codecircuit** [codecircuit/minstructor#13]
```
$ minstructor -n 100 -o data/ './binary' &
$ minstructor -n 50 -o data/ './other-binary' &
```

Can result in data files being overwritten. This is especially dangerous if used with slow backends (e.g. Slurm backend). Multiple solutions exist:

1. `minstructor` requires to get an empty data directory. If two `minstructor` calls are called immediately after each other, data files can be overwritten.
2. `minstructor` temporarily saves the output files somewhere and moves them subsequently to the designated folder. In case of a file conflict, the output file gets a unique hash suffix. This approach is in conflict with the design goal of the `minstructor` to act transparent regarding the generated commands. It is e.g. not transparent put the data files silently somewhere in the home folder.
3. Every data file gets an additional hash suffix, made out of `minstructor` invocation time, the user's name and the host name. This makes a data overwrite very unlikely.
4. `minstructor` checks for other running `minstructor` processes and communicates with them to avoid a data file overwrite. This does not work for NFS and is work intensive.
5. Every call of `minstructor` where data files are created, **must** create a directory where these data files are saved. This keeps the naming of the data files simple, but changes the existing command line interface usage.

**Comment by codecircuit** [comment]
This issue is also related to #9. The only reasonable solution is point 5 mentioned above. For that purpose two variants are possible:

1. `-o /foo/bar/baz` where `baz` is treated as the prefix for the generated output files. Thus directory    `bar` is in this case not allowed to exist already. If `bar` already exists (as file or directory) an error must be thrown. If `-o /foo/bar/` (last slash is important) is given, default output file names are applied.

2. The user can not change the output file name prefix any more. Thus `-o /foo/bar/baz` will create
a directory called `baz` and will save the output files `out_0.txt`, `out_1.txt`, ... into that directory. An additional slash like `-o /foo/bar/baz/` does not have a different effect.

**Comment by mbeutel** [comment]
I agree that point 5 is the most reasonable solution. Also, it is completely race-free because `minstructor` would use the Ruby equivalent of `mkdir` which acts like an atomic compare-exchange operation on the filesystem (it fails if someone else won the race and already created the directory).

However, in the proposed design the user has the burden of choosing a new unique name for every `minstructor` run (which is tedious in scripting scenarios), and of handling the error `minstructor` raises if he forgot to update the subdirectory name. I consider this an unnecessary point of failure; we already have an atomic compare-exchange, so we might as well implement race-free directory allocation right in `minstructor`.

Let me outline one possibility of doing this:

- the user specifies an output directory: `-o /foo/bar/baz`. Here I'm assuming we don't have custom prefixes and `/foo/bar/baz` would be the name of a (possibly existing) directory.
- `minstructor` does the following:
  1. unconditionally create the given directory path, i.e. execute the Ruby equivalent of `mkdir -p /foo/bar/baz`
  2. initialize a counter `C` with 0
  3. execute the Ruby equivalent of `mkdir /foo/bar/baz/$C`
  4. if the directory creation failed, check the reason of failure; if it failed because the directory already exists (Ruby equivalent of `EEXIST` for `mkdir(2)`), increment `C` and loop back to step iii. If it failed for a different reason, print an appropriate error message and abort.
  5. if the directory creation succeeded for a particular counter value `C`, use `/foo/bar/baz/$C` as output directory for this run.

This has consequences for how `mcollector` is used with the output files; where one would currently pass `/foo/bar/baz/*` to `mcollector`, one would then have to use `/foo/bar/baz/*/*`. But note that if #19 is implemented, the user would need no globs at all and could simply pass the same directory to `mcollector`:
```
mcollector -d /foo/bar/baz
```
In the proposed "directories" mode `mcollector` recursively enumerates all files in the given directory, hence the additional level of nesting isn't exposed to the user.

As for custom prefixes, I personally don't use them so I would be fine with not having them.
